// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The details of a a vectorization source, used by Azure OpenAI On Your Data when applying vector search, that is
 * based
 * on an internal embeddings model deployment name in the same Azure OpenAI resource.
 */
@Immutable
public final class OnYourDataDeploymentNameVectorizationSource extends OnYourDataVectorizationSource {

    /*
     * The embedding model deployment name within the same Azure OpenAI resource. This enables you to use vector search
     * without Azure OpenAI api-key and without Azure OpenAI public network access.
     */
    @Generated
    private final String deploymentName;

    /**
     * Creates an instance of OnYourDataDeploymentNameVectorizationSource class.
     *
     * @param deploymentName the deploymentName value to set.
     */
    @Generated
    public OnYourDataDeploymentNameVectorizationSource(String deploymentName) {
        this.deploymentName = deploymentName;
    }

    /**
     * Get the deploymentName property: The embedding model deployment name within the same Azure OpenAI resource. This
     * enables you to use vector search without Azure OpenAI api-key and without Azure OpenAI public network access.
     *
     * @return the deploymentName value.
     */
    @Generated
    public String getDeploymentName() {
        return this.deploymentName;
    }

    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("type", "deployment_name");
        jsonWriter.writeStringField("deployment_name", this.deploymentName);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of OnYourDataDeploymentNameVectorizationSource from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of OnYourDataDeploymentNameVectorizationSource if the JsonReader was pointing to an instance
     * of it, or null if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties or the
     * polymorphic discriminator.
     * @throws IOException If an error occurs while reading the OnYourDataDeploymentNameVectorizationSource.
     */
    public static OnYourDataDeploymentNameVectorizationSource fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String deploymentName = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("type".equals(fieldName)) {
                    String type = reader.getString();
                    if (!"deployment_name".equals(type)) {
                        throw new IllegalStateException(
                            "'type' was expected to be non-null and equal to 'deployment_name'. The found 'type' was '"
                                + type + "'.");
                    }
                } else if ("deployment_name".equals(fieldName)) {
                    deploymentName = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            return new OnYourDataDeploymentNameVectorizationSource(deploymentName);
        });
    }
}
