// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The authentication options for Azure OpenAI On Your Data when using access token.
 */
@Immutable
public final class OnYourDataAccessTokenAuthenticationOptions extends OnYourDataAuthenticationOptions {

    /*
     * The access token to use for authentication.
     */
    @Generated
    private final String accessToken;

    /**
     * Creates an instance of OnYourDataAccessTokenAuthenticationOptions class.
     *
     * @param accessToken the accessToken value to set.
     */
    @Generated
    public OnYourDataAccessTokenAuthenticationOptions(String accessToken) {
        this.accessToken = accessToken;
    }

    /**
     * Get the accessToken property: The access token to use for authentication.
     *
     * @return the accessToken value.
     */
    @Generated
    public String getAccessToken() {
        return this.accessToken;
    }

    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("type", "access_token");
        jsonWriter.writeStringField("access_token", this.accessToken);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of OnYourDataAccessTokenAuthenticationOptions from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of OnYourDataAccessTokenAuthenticationOptions if the JsonReader was pointing to an instance
     * of it, or null if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties or the
     * polymorphic discriminator.
     * @throws IOException If an error occurs while reading the OnYourDataAccessTokenAuthenticationOptions.
     */
    public static OnYourDataAccessTokenAuthenticationOptions fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String accessToken = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("type".equals(fieldName)) {
                    String type = reader.getString();
                    if (!"access_token".equals(type)) {
                        throw new IllegalStateException(
                            "'type' was expected to be non-null and equal to 'access_token'. The found 'type' was '"
                                + type + "'.");
                    }
                } else if ("access_token".equals(fieldName)) {
                    accessToken = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            return new OnYourDataAccessTokenAuthenticationOptions(accessToken);
        });
    }
}
